import { StyleSheet, Platform, TextStyle, ViewStyle } from "react-native";
import { scale, verticalScale, moderateScale } from "react-native-size-matters";

export const shadows = {
  default: Platform.select({
    ios: {
      boxShadowColor: "black",
      boxShadowOffset: { width: 5, height: 5 },
      boxShadowOpacity: 0.3,
      boxShadowRadius: 10,
    },
    android: {
      elevation: 5,
    },
    web: {
      shadowColor: "black",
      shadowOffset: { width: 5, height: 5 },
      shadowOpacity: 0.3,
      shadowRadius: 10,
    },
  }),
};
export const sliderTheme = {
  disableMinTrackTintColor: "#FF7D00",
  maximumTrackTintColor: "gray",
  minimumTrackTintColor: "#FF7D00",
  bubbleBackgroundColor: "#FF7D00",
  bubbleTextColor: "black",
};
export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#141928",
    paddingHorizontal: Math.round(scale(30)),
    paddingVertical: verticalScale(20),
    justifyContent: "space-between",
    alignItems: "center",
  },
  containerCentered: {
    flex: 1,
    backgroundColor: "#141928",
    paddingHorizontal: Math.round(scale(30)),
    paddingVertical: verticalScale(20),
    justifyContent: "center",
    gap: Math.round(scale(40)),
    alignItems: "center",
  },
  indexBackground: {
    width: Math.round(scale(300)),
    height: verticalScale(300),
    alignSelf: "center",
  },
  welcomeTitle: {
    color: "white",
    textAlign: "center",
    fontSize: Math.round(scale(30)),
    fontWeight: "bold",
    textTransform: "uppercase",
    letterSpacing: 2,
    textShadow: {
      color: "white",
      offset: { width: 1, height: 1 },
      radius: 4,
    },
    fontFamily: "monospace",
  } as TextStyle,

  // ! Option button
  mainBtn: {
    backgroundColor: "#FF7D00",
    borderRadius: 10,
    width: Math.round(scale(170)),
    alignSelf: "center",
    ...shadows.default,
  },
  mainBtnTxt: {
    color: "black",
    paddingVertical: Math.round(scale(10)),
    paddingHorizontal: Math.round(scale(10)),
    fontWeight: "bold",
    fontSize: Math.round(scale(16)),
    textAlign: "center",
  },
  mainBtnMedium: {
    backgroundColor: "#FF7D00",
    borderRadius: 10,
    width: Math.round(scale(120)),
    alignSelf: "center",
    ...shadows.default,
  },
  mainBtnMediumTxt: {
    color: "black",
    paddingVertical: Math.round(scale(10)),
    fontWeight: "bold",
    fontSize: Math.round(scale(14)),
    textAlign: "center",
  },
  mainBtnSmall: {
    backgroundColor: "#FF7D00",
    borderRadius: 10,
    width: Math.round(scale(100)),
    alignSelf: "center",
    ...shadows.default,
  },
  mainBtnSmallTxt: {
    color: "black",
    fontWeight: "bold",
    fontSize: Math.round(scale(12)),
    textAlign: "center",
  },

  profileImg: {
    width: Math.round(scale(100)),
    height: Math.round(scale(100)),
    margin: Math.round(scale(10)),
    borderRadius: 8,
    ...shadows.default,
  },
  historyContainer: {
    height: verticalScale(300),
    width: Math.round(scale(300)),
    justifyContent: "space-around",
    backgroundColor: "#1B263B",
    padding: Math.round(scale(10)),
    borderRadius: 10,
    ...shadows.default,
  },
  historyHeader: {
    flexDirection: "row",
    paddingBottom: Math.round(scale(10)),
    borderBottomWidth: 2,
  },
  historyHeaderCell: {
    flex: 1,
    textAlign: "center",
    fontWeight: "bold",
    color: "white",
  },
  historyRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "black",
  },
  historyCell: {
    flex: 1,
    margin: "auto",
    textAlign: "center",
    padding: Math.round(scale(10)),
    color: "white",
  },
  historySpecBtn: {
    flex: 1,
    backgroundColor: "rgb(0, 140, 255)",
    borderRadius: 6,
    margin: "auto",
    marginHorizontal: Math.round(scale(5)),
    alignItems: "center",
    width: "100%",
    ...shadows.default,
  },
  historyPrintBtn: {
    flex: 1,
    backgroundColor: "rgb(0, 255, 98)",
    borderRadius: 6,
    margin: "auto",
    marginHorizontal: Math.round(scale(5)),
    alignItems: "center",
    width: "100%",
    ...shadows.default,
  },

  // Option styles
  optionCard: {
    backgroundColor: "#1B263B",
    padding: Math.round(scale(20)),
    borderRadius: 20,
    alignItems: "center",
    ...shadows.default,
    height: Math.round(scale(230)),
    width: Math.round(scale(230)),
    marginTop: "auto",
    marginBottom: "auto",
    justifyContent: "space-around", // Căn đều khoảng cách giữa các phần tử
  },
  header: {
    justifyContent: "center",
    alignItems: "center",
    marginTop: Math.round(scale(10)),
  },
  navTitle: {
    textAlign: "center",
    fontSize: Math.round(scale(24)),
    fontWeight: "bold",
    color: "white",
    textTransform: "uppercase",
    letterSpacing: 2,
    fontFamily: "monospace",
  },

  // ! Grid
  gridContainer: {
    flex: 1,
    marginVertical: verticalScale(5),
    width: "100%",
  },
  gridItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#1B263B",
    padding: Math.round(scale(20)),
    borderRadius: 8,
    ...shadows.default,
    width: "100%",
    marginBottom: verticalScale(20),
  },
  gridImage: {
    // width: Math.round(scale(80)),
    // height: Math.round(scale(80)),
    marginRight: Math.round(scale(20)),
  },
  gridTextContainer: {
    flex: 1,
  },

  title: {
    fontSize: Math.round(scale(14)),
    fontWeight: "bold",
    color: "#FF7D00",
    textTransform: "uppercase",
  },
  subtitle: {
    color: "white",
    fontSize: Math.round(scale(12)),
  },

  // ! Menu
  menu: {
    backgroundColor: "#fff",
    borderRadius: 15,
    width: "50%",
  },
  menuContent: {
    backgroundColor: "white",
  },
  menuItem: {
    color: "black",
    fontWeight: "bold",
    fontSize: Math.round(scale(14)),
    textAlign: "left",
  },

  // ! Component
  componentTitle: {
    fontSize: Math.round(scale(32)),
    fontWeight: "bold",
    color: "white",
    textTransform: "uppercase",
    letterSpacing: 2,
    textAlign: "center",
  },
  componentImg: {
    width: Math.round(scale(200)),
    height: Math.round(scale(200)),
    marginBottom: Math.round(scale(10)),
  },
  componentInfoContainer: {
    alignSelf: "flex-start",
    padding: Math.round(scale(20)),
  },
  componentInfo: {
    fontSize: Math.round(scale(16)),
    color: "#FF7D00",
    fontWeight: "bold",
    marginBottom: Math.round(scale(10)),
  },
  componentInfoName: {
    fontWeight: "normal",
    color: "white",
  },

  // ! Dropdown
  dropdown: {
    flex: 1,
    marginVertical: verticalScale(5),
    width: "100%",
    alignSelf: "center",
    justifyContent: "flex-start",
    backgroundColor: "#1B263B",
    borderRadius: 10,
    borderColor: "transparent",
    ...shadows.default,
  },
  dropdownContainer: {
    backgroundColor: "#1B263B",
    borderColor: "transparent",
    width: "100%",
    alignSelf: "center",
  },

  // Design image preview
  designImgPreview: {
    width: "100%",
    height: verticalScale(300),
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#FF7D00",
  },

  // Design Page Style
  pageTitle: {
    fontSize: Math.round(scale(20)),
    fontWeight: "bold",
    color: "white",
    textTransform: "uppercase",
    textAlign: "center",
  },
  inputContainer: {
    maxHeight: verticalScale(450),
    width: "100%",
    backgroundColor: "#1B263B",
    padding: Math.round(scale(20)),
    borderRadius: 10,
    ...shadows.default,
  },
  inputFieldLabel: {
    fontSize: Math.round(scale(14)),
    fontStyle: "italic",
    color: "rgb(173, 181, 201)",
    marginBottom: Math.round(scale(5)),
  },
  inputField: {
    borderWidth: 2,
    borderColor: "#FF7D00",
    borderRadius: 5,
    marginBottom: Math.round(scale(5)),
    paddingHorizontal: Math.round(scale(10)),
    paddingVertical: Math.round(scale(4)),
    fontSize: Math.round(scale(14)),
    color: "white",
  },

  // Adjustment Page Style
  resultContainer: {
    width: "100%",
    backgroundColor: "#1B263B",
    padding: Math.round(scale(20)),
    borderRadius: 10,
    ...shadows.default,
  },
  resultText: {
    fontSize: Math.round(scale(16)),
    color: "white",
  },
  colContainer: {
    maxHeight: verticalScale(300),
    flexDirection: "row",
    justifyContent: "space-around",
    width: "100%",
    padding: Math.round(scale(10)),
    backgroundColor: "#1B263B",
    borderRadius: 10,
    ...shadows.default,
  },
  tableContainer: {
    flex: 1,
  },
  tableContainerPad10: {
    flex: 1,
    padding: Math.round(scale(10)),
    justifyContent: "space-around",
  },
  tableTitle: {
    color: "white",
    fontSize: Math.round(scale(16)),
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: verticalScale(10),
  },
  parameterRow: {
    marginBottom: Math.round(scale(5)),
    marginHorizontal: Math.round(scale(15)),
  },
  paramType: {
    color: "white",
    fontSize: Math.round(scale(14)),
    fontStyle: "italic",
  },
  slider: {
    width: "80%",
    marginVertical: verticalScale(20),
  },

  // Select Stuff Page Style
  selectContainer: {
    flex: 1,
    maxHeight: verticalScale(300),
    flexDirection: "row",
    justifyContent: "space-around",
    width: "100%",
    backgroundColor: "#1B263B",
    padding: Math.round(scale(10)),
    borderRadius: 10,
    ...shadows.default,
  },
  selectItem: {
    marginBottom: Math.round(scale(10)),
    padding: Math.round(scale(10)),
    backgroundColor: "#1f2b42",
    borderRadius: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: scale(10),
  },
  selectName: {
    fontSize: Math.round(scale(16)),
    fontWeight: "bold",
    color: "#FF7D00",
    marginBottom: verticalScale(10),
  },
  selectDetails: {
    fontSize: Math.round(scale(12)),
    color: "white",
  },
  noDataWarn: {
    color: "white",
    textAlign: "center",
    fontWeight: "bold",
    fontSize: Math.round(scale(24)),
  },
  specContainer: {
    height: verticalScale(450),
    // maxHeight: verticalScale(450),
    width: "100%",
    justifyContent: "space-between",
    backgroundColor: "#1B263B",
    padding: Math.round(scale(10)),
    borderRadius: 10,
    flexDirection: "row",
    ...shadows.default,
  },
  specContainerRow: {
    maxHeight: verticalScale(450),
    width: "100%",
    justifyContent: "space-between",
    backgroundColor: "#1B263B",
    padding: Math.round(scale(10)),
    borderRadius: 10,
    flexDirection: "column",
    ...shadows.default,
  },
  specHeader: {
    flex: 1,
    flexDirection: "column",
    height: "100%",
    justifyContent: "space-around",
    alignSelf: "center",
    borderRightWidth: 2,
    borderColor: "white",
  },
  specHeaderCell: {
    flex: 1,
    flexWrap: "wrap",
    paddingHorizontal: Math.round(scale(5)),
    alignContent: "center",
    textAlign: "center",
    fontWeight: "bold",
    color: "#FF7D00",
  },
  specHeaderRow: {
    flexDirection: "row",
    width: "100%",
    justifyContent: "space-around",
    paddingVertical: Math.round(scale(10)),
    alignSelf: "center",
    borderBottomWidth: 2,
    borderColor: "white",
  },
  specHeaderRowCell: {
    flexWrap: "wrap",
    paddingHorizontal: Math.round(scale(5)),
    alignContent: "center",
    textAlign: "center",
    fontWeight: "bold",
    color: "white",
  },
  specCol: {
    flex: 1,
    // height: "100%",
    flexDirection: "column",
    justifyContent: "space-around",
    borderRightWidth: 1,
    borderBottomColor: "white",
    borderRightColor: "white",
  },
  specRow: {
    flex: 1,
    height: "100%",
    flexDirection: "row",
    justifyContent: "space-around",
    borderBottomWidth: 1,
    borderBottomColor: "white",
  },
  specCell: {
    flex: 1,
    flexWrap: "wrap",
    paddingHorizontal: Math.round(scale(5)),
    alignContent: "center",
    textAlign: "center",
    borderTopWidth: 1,
    borderColor: "white",
    color: "white",
  },
  specCellRow: {
    flex: 1,
    flexWrap: "wrap",
    paddingHorizontal: Math.round(scale(5)),
    paddingVertical: Math.round(scale(15)),
    alignContent: "center",
    textAlign: "center",
    color: "white",
  },
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)", // mờ nền
    justifyContent: "center",
    alignItems: "center",
  },
  modalView: {
    backgroundColor: "#1B263B",
    padding: Math.round(scale(20)),
    borderRadius: 10,
    width: "90%",
    alignItems: "center",
    rowGap: Math.round(scale(20)),
  },
});
