import { StyleSheet, Platform, TextStyle, ViewStyle } from "react-native";
import { scale, verticalScale, moderateScale } from "react-native-size-matters";
import { Colors } from "./Colors";

export const shadows = {
  default: Platform.select({
    ios: {
      boxShadowColor: Colors.text.secondary,
      boxShadowOffset: { width: 5, height: 5 },
      boxShadowOpacity: 0.3,
      boxShadowRadius: 10,
    },
    android: {
      elevation: 5,
    },
    web: {
      shadowColor: Colors.text.secondary,
      shadowOffset: { width: 5, height: 5 },
      shadowOpacity: 0.3,
      shadowRadius: 10,
    },
  }),
};

export const sliderTheme = {
  disableMinTrackTintColor: Colors.primary,
  maximumTrackTintColor: Colors.unselected,
  minimumTrackTintColor: Colors.primary,
  bubbleBackgroundColor: Colors.primary,
  bubbleTextColor: Colors.text.secondary,
};

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
    paddingHorizontal: Math.round(scale(30)),
    paddingVertical: verticalScale(30),
    justifyContent: "space-between",
    alignItems: "center",
  },
  containerCentered: {
    flex: 1,
    backgroundColor: Colors.background,
    paddingHorizontal: Math.round(scale(30)),
    paddingVertical: verticalScale(30),
    gap: Math.round(scale(40)),
    alignItems: "center",
    justifyContent: "center",
  },
  containerStart: {
    flex: 1,
    backgroundColor: Colors.background,
    paddingTop: verticalScale(30),
    paddingBottom: verticalScale(50),
    gap: Math.round(scale(10)),
    alignItems: "center",
  },
  indexBackground: {
    width: Math.round(scale(300)),
    height: verticalScale(300),
    alignSelf: "center",
  },
  welcomeTitle: {
    color: Colors.text.primary,
    textAlign: "center",
    fontSize: Math.round(scale(30)),
    fontWeight: "bold",
    textTransform: "uppercase",
    letterSpacing: 2,
    textShadow: {
      color: Colors.text.primary,
      offset: { width: 1, height: 1 },
      radius: 4,
    },
    fontFamily: "monospace",
  } as TextStyle,

  headerFullStyle: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
  },
  headerRightIcon: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    paddingLeft: scale(10),
  },
  headerLeftIcon: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    paddingRight: scale(10),
  },
  headerNoIcon: {
    backgroundColor: Colors.background,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    marginTop: scale(10),
  },

  // ! Option button
  mainBtn: {
    backgroundColor: Colors.primary,
    borderRadius: 10,
    width: Math.round(scale(170)),
    alignSelf: "center",
    ...shadows.default,
  },
  mainBtnTxt: {
    color: Colors.text.secondary,
    paddingVertical: Math.round(scale(10)),
    paddingHorizontal: Math.round(scale(10)),
    fontWeight: "bold",
    fontSize: Math.round(scale(16)),
    textAlign: "center",
  },
  mainBtnMedium: {
    backgroundColor: Colors.primary,
    borderRadius: 10,
    width: Math.round(scale(120)),
    alignSelf: "center",
    ...shadows.default,
  },
  mainBtnMediumTxt: {
    color: Colors.text.secondary,
    paddingVertical: Math.round(scale(10)),
    fontWeight: "bold",
    fontSize: Math.round(scale(14)),
    textAlign: "center",
  },
  mainBtnSmall: {
    backgroundColor: Colors.primary,
    borderRadius: 10,
    width: Math.round(scale(100)),
    alignSelf: "center",
    ...shadows.default,
  },
  mainBtnSmallTxt: {
    color: Colors.text.secondary,
    fontWeight: "bold",
    fontSize: Math.round(scale(12)),
    textAlign: "center",
  },
  deleteBtn: {
    textAlign: "center",
    backgroundColor: Colors.text.error,
    borderRadius: 10,
    width: "100%",
    marginTop: scale(10),
    ...shadows.default,
  },
  deleteBtnTxt: {
    color: Colors.text.primary,
    fontWeight: "bold",
    fontSize: Math.round(scale(13)),
    textAlign: "center",
  },

  profileImg: {
    width: Math.round(scale(100)),
    height: Math.round(scale(100)),
    margin: Math.round(scale(10)),
    borderRadius: 8,
    ...shadows.default,
  },
  historyContainer: {
    height: verticalScale(300),
    width: "90%",
    justifyContent: "space-between",
    backgroundColor: Colors.card,
    padding: Math.round(scale(10)),
    borderRadius: 10,
    ...shadows.default,
  },
  historyHeader: {
    flexDirection: "row",
    paddingBottom: Math.round(scale(10)),
    borderBottomWidth: 2,
  },
  historyHeaderCell: {
    flex: 1,
    textAlign: "center",
    fontWeight: "bold",
    color: Colors.text.primary,
  },
  historyRow: {
    backgroundColor: Colors.card,
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "black",
  },
  historyCell: {
    flex: 1,
    fontSize: Math.round(scale(11)),
    margin: "auto",
    textAlign: "center",
    padding: Math.round(scale(10)),
    color: Colors.text.primary,
  },
  historyStatusCell: {
    flex: 1,
    margin: "auto",
    textAlign: "center",
    color: Colors.text.secondary,
    borderRadius: 3,
    fontSize: Math.round(scale(10)),
    paddingHorizontal: Math.round(scale(5)),
    ...shadows.default,
  },
  utilBtnContainer: {
    flex: 1,
    backgroundColor: "rgba(39, 43, 49, 0.49)",
    margin: "auto",
    alignItems: "center",
    marginHorizontal: Math.round(scale(10)),
    width: scale(80),
    ...shadows.default,
  },
  utilBtnTxt: {
    color: Colors.text.primary,
    fontSize: scale(12),
  },

  homeCard: {
    // flex: 1,
    backgroundColor: Colors.card,
    padding: Math.round(scale(20)),
    borderRadius: 20,
    alignItems: "center",
    ...shadows.default,
    // height: "100%",
    margin: scale(5),
    marginHorizontal: scale(20),
    justifyContent: "space-between",
    flexDirection: "row",
  },
  homeCardCol: {
    margin: "auto",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: verticalScale(20),
  },
  homeCardTxt: {
    color: Colors.text.primary,
    fontSize: scale(12),
  },
  homeCardMedTxt: {
    color: Colors.text.primary,
    fontSize: scale(16),
    alignSelf: "center",
    textAlign: "center",
  },
  homeCardBigTxt: {
    color: Colors.text.primary,
    fontSize: scale(20),
    alignSelf: "center",
    textAlign: "center",
  },
  homeCard1x2: {
    flex: 1,
    backgroundColor: Colors.card,
    padding: Math.round(scale(20)),
    borderRadius: 20,
    height: verticalScale(320),
    alignItems: "flex-start",
    justifyContent: "space-between",
    marginHorizontal: scale(10),
    ...shadows.default,
  },
  homeColContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "space-between",
    flexDirection: "row",
    marginHorizontal: scale(10),
  },
  homeRowContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "space-between",
    flexDirection: "column",
    rowGap: scale(20),
    marginHorizontal: scale(10),
  },
  homeCard1x1: {
    width: "100%",
    backgroundColor: Colors.card,
    padding: Math.round(scale(20)),
    borderRadius: 20,
    height: verticalScale(150),
    alignItems: "flex-start",
    justifyContent: "space-between",
    marginHorizontal: scale(10),
    ...shadows.default,
  },

  scrollContainer: {
    marginBottom: verticalScale(30),
    gap: Math.round(verticalScale(30)),
    alignItems: "center",
  },
  // Option styles
  optionCard: {
    backgroundColor: Colors.card,
    padding: Math.round(scale(10)),
    borderRadius: 20,
    alignItems: "center",
    ...shadows.default,
    height: "100%",
    margin: scale(5),
    justifyContent: "space-around",
  },
  // header: {
  //   justifyContent: "center",
  //   alignItems: "center",
  //   marginTop: Math.round(scale(10)),
  // },
  navTitle: {
    textAlign: "center",
    fontSize: Math.round(scale(24)),
    fontWeight: "bold",
    color: Colors.text.primary,
    textTransform: "uppercase",
    letterSpacing: 2,
    fontFamily: "monospace",
  },

  // ! Grid
  gridContainer: {
    flex: 1,
    marginVertical: verticalScale(5),
    width: "100%",
  },
  gridItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.card,
    padding: Math.round(scale(20)),
    borderRadius: 8,
    ...shadows.default,
    width: scale(275),
  },
  gridImage: {
    marginRight: Math.round(scale(20)),
  },
  gridTextContainer: {
    flex: 1,
  },

  title: {
    fontSize: Math.round(scale(14)),
    fontWeight: "bold",
    color: Colors.primary,
    textTransform: "uppercase",
  },
  subtitle: {
    color: Colors.text.primary,
    fontSize: Math.round(scale(12)),
  },

  // ! Menu
  menu: {
    backgroundColor: Colors.text.primary,
    borderRadius: 15,
    width: "50%",
  },
  menuContent: {
    backgroundColor: Colors.text.primary,
  },
  menuItem: {
    color: Colors.text.secondary,
    fontWeight: "bold",
    fontSize: Math.round(scale(14)),
    textAlign: "left",
  },

  // ! Component
  componentTitle: {
    fontSize: Math.round(scale(26)),
    fontWeight: "bold",
    color: Colors.text.primary,
    textTransform: "uppercase",
    letterSpacing: 2,
    textAlign: "center",
  },
  componentImg: {
    // width: Math.round(scale(200)),
    // height: Math.round(scale(200)),
    margin: Math.round(scale(10)),
  },
  componentInfoContainer: {
    alignSelf: "flex-start",
  },
  componentInfo: {
    fontSize: Math.round(scale(14)),
    color: Colors.primary,
    fontWeight: "bold",
    marginBottom: Math.round(scale(5)),
  },
  componentInfoName: {
    fontWeight: "normal",
    color: Colors.text.primary,
  },

  // ! Dropdown
  dropdown: {
    flex: 1,
    marginVertical: verticalScale(5),
    width: "100%",
    alignSelf: "center",
    justifyContent: "flex-start",
    backgroundColor: Colors.card,
    borderRadius: 10,
    borderColor: Colors.border.transparent,
    ...shadows.default,
  },
  dropdownContainer: {
    backgroundColor: Colors.card,
    borderColor: Colors.border.transparent,
    width: "100%",
    alignSelf: "center",
  },

  // Design image preview
  designImgPreview: {
    width: "100%",
    height: verticalScale(300),
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.primary,
  },

  // Design Page Style
  pageTitle: {
    fontSize: Math.round(scale(18)),
    fontWeight: "bold",
    color: Colors.text.primary,
    textTransform: "uppercase",
    textAlign: "center",
  },
  inputContainer: {
    maxHeight: verticalScale(450),
    width: "100%",
    backgroundColor: Colors.card,
    padding: Math.round(scale(20)),
    borderRadius: 10,
    ...shadows.default,
  },
  inputFieldLabel: {
    fontSize: Math.round(scale(14)),
    fontStyle: "italic",
    color: Colors.text.muted,
    marginBottom: Math.round(scale(5)),
  },
  inputField: {
    borderWidth: 2,
    borderColor: Colors.primary,
    borderRadius: 5,
    marginBottom: Math.round(scale(5)),
    paddingHorizontal: Math.round(scale(10)),
    paddingVertical: Math.round(scale(4)),
    fontSize: Math.round(scale(14)),
    color: Colors.text.primary,
  },

  // Adjustment Page Style
  resultContainer: {
    width: "100%",
    backgroundColor: Colors.card,
    padding: Math.round(scale(20)),
    borderRadius: 10,
    ...shadows.default,
  },
  resultText: {
    fontSize: Math.round(scale(16)),
    color: Colors.text.primary,
  },
  colContainer: {
    maxHeight: verticalScale(300),
    flexDirection: "row",
    justifyContent: "space-around",
    width: "100%",
    padding: Math.round(scale(10)),
    backgroundColor: Colors.card,
    borderRadius: 10,
    ...shadows.default,
  },
  tableContainer: {
    flex: 1,
  },
  tableContainerPad10: {
    flex: 1,
    padding: Math.round(scale(10)),
    justifyContent: "space-around",
  },
  tableTitle: {
    color: Colors.text.primary,
    fontSize: Math.round(scale(16)),
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: verticalScale(10),
  },
  parameterRow: {
    marginBottom: Math.round(scale(5)),
    marginHorizontal: Math.round(scale(15)),
  },
  paramType: {
    color: Colors.text.primary,
    fontSize: Math.round(scale(14)),
    fontStyle: "italic",
  },
  slider: {
    width: "80%",
    marginVertical: verticalScale(20),
  },

  // Select Stuff Page Style
  selectContainer: {
    flex: 1,
    maxHeight: verticalScale(300),
    flexDirection: "row",
    justifyContent: "space-around",
    width: "100%",
    backgroundColor: Colors.card,
    padding: Math.round(scale(10)),
    borderRadius: 10,
    ...shadows.default,
  },
  selectItem: {
    marginBottom: Math.round(scale(10)),
    padding: Math.round(scale(10)),
    backgroundColor: Colors.cardDark,
    borderRadius: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: scale(10),
  },
  selectName: {
    fontSize: Math.round(scale(16)),
    fontWeight: "bold",
    color: Colors.primary,
    marginBottom: verticalScale(10),
  },
  selectDetails: {
    fontSize: Math.round(scale(12)),
    color: Colors.text.primary,
  },
  noDataWarn: {
    color: Colors.text.primary,
    textAlign: "center",
    fontWeight: "bold",
    fontSize: Math.round(scale(24)),
  },
  specContainer: {
    height: verticalScale(450),
    // maxHeight: verticalScale(450),
    width: "100%",
    justifyContent: "space-between",
    backgroundColor: Colors.card,
    padding: Math.round(scale(10)),
    borderRadius: 10,
    flexDirection: "row",
    ...shadows.default,
  },
  specContainerRow: {
    maxHeight: verticalScale(450),
    width: "100%",
    justifyContent: "space-between",
    backgroundColor: Colors.card,
    padding: Math.round(scale(10)),
    borderRadius: 10,
    flexDirection: "column",
    ...shadows.default,
  },
  specHeader: {
    flex: 1,
    flexDirection: "column",
    height: "100%",
    justifyContent: "space-around",
    alignSelf: "center",
    borderRightWidth: 2,
    borderColor: Colors.border.primary,
  },
  specHeaderCell: {
    flex: 1,
    flexWrap: "wrap",
    paddingHorizontal: Math.round(scale(5)),
    alignContent: "center",
    textAlign: "center",
    fontWeight: "bold",
    color: Colors.primary,
  },
  specHeaderRow: {
    flexDirection: "row",
    width: "100%",
    justifyContent: "space-around",
    paddingVertical: Math.round(scale(10)),
    alignSelf: "center",
    borderBottomWidth: 2,
    borderColor: Colors.border.primary,
  },
  specHeaderRowCell: {
    flexWrap: "wrap",
    paddingHorizontal: Math.round(scale(5)),
    alignContent: "center",
    textAlign: "center",
    fontWeight: "bold",
    color: Colors.text.primary,
  },
  specCol: {
    flex: 1,
    // height: "100%",
    flexDirection: "column",
    justifyContent: "space-around",
    borderRightWidth: 1,
    borderBottomColor: Colors.border.primary,
    borderRightColor: Colors.border.primary,
  },
  specRow: {
    flex: 1,
    height: "100%",
    flexDirection: "row",
    justifyContent: "space-around",
    borderBottomWidth: 1,
    borderBottomColor: Colors.border.primary,
  },
  specCell: {
    flex: 1,
    flexWrap: "wrap",
    paddingHorizontal: Math.round(scale(5)),
    alignContent: "center",
    textAlign: "center",
    borderTopWidth: 1,
    borderColor: Colors.border.primary,
    color: Colors.text.primary,
  },
  specCellRow: {
    flex: 1,
    flexWrap: "wrap",
    paddingHorizontal: Math.round(scale(5)),
    paddingVertical: Math.round(scale(15)),
    alignContent: "center",
    textAlign: "center",
    color: Colors.text.primary,
  },
  overlay: {
    flex: 1,
    backgroundColor: Colors.overlay,
    justifyContent: "center",
    alignItems: "center",
  },
  modalView: {
    backgroundColor: Colors.card,
    padding: Math.round(scale(20)),
    borderRadius: 10,
    width: "90%",
    alignItems: "center",
    marginHorizontal: "auto",
    rowGap: Math.round(scale(20)),
  },
  modalMediumTxt: {
    color: Colors.text.primary,
    fontSize: Math.round(scale(16)),
    textAlign: "center",
  },
  bottomSheetContainer: {
    paddingHorizontal: Math.round(scale(10)),
  },
  bottomSheetFlatListContainer: {
    paddingBottom: Math.round(verticalScale(20)),
  },
  bottomSheetContent: {
    marginHorizontal: Math.round(scale(20)),
    marginVertical: Math.round(scale(5)),
  },
  bottomSheetLargeTxt: {
    color: Colors.text.lightAccent,
    fontSize: Math.round(scale(14)),
    lineHeight: Math.round(verticalScale(30)),
  },
  bottomSheetNormalTxt: {
    color: Colors.text.primary,
    fontSize: Math.round(scale(12)),
  },
  bottomSheetSmallTxt: {
    color: Colors.text.muted,
    fontSize: Math.round(scale(11)),
    fontStyle: "italic",
    lineHeight: Math.round(verticalScale(25)),
  },
  bottomSheetSmallBoldTxt: {
    color: Colors.text.muted,
    fontSize: Math.round(scale(11)),
    fontStyle: "italic",
    fontWeight: "bold",
    lineHeight: Math.round(verticalScale(25)),
  },
});
